<?php
/**
 * Created by PhpStorm.
 * User: yaseen
 * Date: 11/16/2017
 * Time: 9:40 PM
 */

namespace App\Controllers\Admin;


use Bootstrap\Controller;

class User extends Controller
{
    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        echo 'admin co';
    }

}