<?php
/**
 * Created by PhpStorm.
 * User: yaseen
 * Date: 11/20/2017
 * Time: 4:16 AM
 */

namespace App\Models;


use Bootstrap\Model;

class Post extends Model
{
 public $table ='posts';
public function __construct()
{
    return parent::connect(); // TODO: Change the autogenerated stub
}

}